{{- if and .Values.gotify.enabled .Values.gotify.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: {{ .Values.namespace }}
  labels:
    app: gotify
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.gotify.persistence.storageClass }}
  storageClassName: {{ .Values.gotify.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gotify.persistence.size }}
{{- end }}
