[project]
name = "vm-iot-simulator"
version = "0.2.0"
description = "Industrial Vending Machine IoT Simulator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "paho-mqtt>=2.1.0",
    "faker>=33.0.0",
    "python-dotenv>=1.0.1",
]

[tool.uv]
managed = true
