apiVersion: 1

contactPoints:
#  - orgId: 1
#    name: gotify
#    receivers:
#      - uid: gotify-webhook
#        type: webhook
#        settings:
#          url: http://gotify:80/message
#          httpMethod: POST
#          maxAlerts: 0
#        secureSettings:
#          authorization_header: ${GOTIFY_APP_TOKEN}
