apiVersion: 1

policies:
  - orgId: 1
    receiver: gotify
    group_by:
      - alertname
      - grafana_folder
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: gotify
        matchers:
          - severity = warning
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 12h
      - receiver: gotify
        matchers:
          - severity = critical
        group_wait: 5s
        group_interval: 2m
        repeat_interval: 4h
