{{- if .Values.authelia.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: authelia-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: authelia
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  # Resend SMTP 配置
  resend-username: {{ .Values.authelia.smtp.username | quote }}
  resend-api-key: {{ .Values.authelia.smtp.apiKey | quote }}
{{- end }}
