{{- if .Values.centrifugo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: centrifugo-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: centrifugo
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  token-secret: {{ .Values.centrifugo.tokenSecret | default "change-this-token-secret" | quote }}
  api-key: {{ .Values.centrifugo.apiKey | default "change-this-api-key" | quote }}
  admin-password: {{ .Values.centrifugo.adminPassword | default "change-this-admin-password" | quote }}
  admin-secret: {{ .Values.centrifugo.adminSecret | default "change-this-admin-secret" | quote }}
{{- end }}
