{{- if .Values.gotify.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gotify-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: gotify
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  admin-password: {{ .Values.gotify.adminPassword | default "change-this-password" | quote }}
{{- end }}
