{{- if .Values.meilisearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: meilisearch
type: Opaque
stringData:
  master-key: {{ .Values.meilisearch.masterKey | default "changeme-meilisearch-key" | quote }}
{{- end }}
