{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: {{ .Values.namespace }}
  labels:
    app: mosquitto
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.mosquitto.service.type }}
  ports:
  - port: {{ .Values.mosquitto.service.port }}
    targetPort: mqtt
    protocol: TCP
    name: mqtt
  - port: 9001
    targetPort: websocket
    protocol: TCP
    name: websocket
  selector:
    app: mosquitto
{{- end }}
