{{- if .Values.phpFpm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: {{ .Values.namespace }}
  labels:
    app: php-fpm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.phpFpm.service.type }}
  ports:
  - name: http
    port: {{ .Values.phpFpm.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    app: php-fpm
{{- end }}
