services:
  postgres17:
    build:
      context: .
      args:
        - POSTGRES_VERSION=17.6-alpine
    container_name: postgres17
    restart: always
    volumes:
      - ${CONFIG_PATH}postgres17/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${DATA_PATH}postgres:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_CONFIG_PROFILE=${POSTGRES_CONFIG_PROFILE:-1c1g}
    networks:
      - backend
      - frontend
