apiVersion: 1

deleteDatasources:
  - name: iot-vending-timescaledb
    orgId: 1

datasources:
  - name: IoT Vending Machine
    type: postgres
    uid: iot-vending-timescaledb
    access: proxy
    url: postgres:5432
    user: postgres
    database: lunchbox
    basicAuth: false
    isDefault: true
    jsonData:
      database: lunchbox
      sslmode: 'disable'
      postgresVersion: 1500 # Use 1500 as safe stable version
      timescaledb: true
    secureJsonData:
      password: '598f18a1c99d539ced6631add2b428b3'
