services:
  mosquitto:
    build:
      context: .
    container_name: mosquitto
    restart: always
    ports:
      - "${MQTT_PORT:-1883}:1883"
    volumes:
      - ${CONFIG_PATH}/mosquitto/config:/mosquitto/config
      - ${DATA_PATH}mosquitto/data:/mosquitto/data
      - ${LOG_PATH}mosquitto/log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_ALLOW_ANONYMOUS=${MQTT_ALLOW_ANONYMOUS:-false}
      - SITE_ADDRESS=${SITE_ADDRESS}
    networks:
      - backend
      - frontend
#    depends_on:
#      caddy:
#        condition: service_started
