services:
  go-access:
    image: jiaoio/goaccess:latest
    restart: always
    volumes:
      - ${LOG_PATH}caddy:/srv/logs
    environment:
      - GOACCESS_WS_URL=wss://clogs.${SITE_ADDRESS}:443
      - GOACCESS_OUTPUT=/srv/logs/report.html
    depends_on:
      - caddy
    networks:
      - backend
