services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.2
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ${CONFIG_PATH}cloudflared:/etc/cloudflared
    networks:
      - backend
      - frontend