services:
  php-schedule:
    build:
      context: .
    container_name: php-schedule
    restart: always
    environment:
      - APP_PATH=${APP_PATH}
      - APP_ENV=${APP_ENV}
    volumes:
      - ${APP_CODE_PATH}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    networks:
      - backend
    depends_on:
      - php-horizon
