services:
  beszel:
    container_name: beszel
    build:
      context: .
      dockerfile: Dockerfile
    # 默认用户名: ailuoga166@gmail.com 密码: ailuoga166@gmail.com
    environment:
      - USER_EMAIL=${BESZEL_USER_EMAIL:-ailuoga166@gmail.com}
      - USER_PASSWORD=${BESZEL_USER_PASSWORD:-ailuoga166@gmail.com}
    restart: always
    ports:
      - "${BESZEL_PORT:-8090}:8090"
    volumes:
      - ${DATA_PATH}beszel:/beszel_data
    networks:
      - backend
      - frontend
